version: 2.1

machine:
  services:
    - docker

dependencies:
  cache_directories:
    - ~/docker

jobs:
  build:
    working_directory: ~/customer_registry_service
    docker:
      - image: circleci/openjdk:8
      - image: circleci/mongo:4.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - app-cache-{{ checksum "build.sbt" }}
            - app-cache-v1

      - save_cache:
          key: app-cache-{{ checksum "build.sbt" }}
          paths:
            - target/resolution-cache
            - target/streams
            - project/target/resolution-cache
            - project/target/streams
            - ~/.sbt
            - ~/.ivy2/cache
      - save_cache:
          # Change this key to start the next build with a fully clean cache and forget old scala, sbt and library versions
          key: app-cache-v1
          paths:
            - ~/.sbt
            - ~/.ivy2/cache

      - run:
          name: "Unit tests"
          command:
            sbt unit exit

      - run:
          name: "Integration tests"
          command:
            sbt integration exit

      - store_test_results:
          path: target/test-reports

deployment:
  staging:
    branch: master
    commands:
      - export ARTIFACT_NAME=registry.heroku.com/visioni40/customer_registry_service
      - export GIT_COMMIT=$CIRCLE_SHA1
      - sbt docker:publishLocal
      - docker login --email=$HEROKU_LOGIN --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - docker push $ARTIFACT_NAME:$GIT_COMMIT