version: 2.1

dependencies:
  cache_directories:
    - ~/docker

container_name: &container_name
  gcr.io/vision-i40/customer_registry_service

setup_gcp_credentials: &setup_gcp_credentials
  run:
    name: Setup GCP credentials
    command: |
      echo  $SERVICE_ACCOUNT_CONTENT | base64 -d > gcp.json
      gcloud auth activate-service-account --key-file gcp.json
      gcloud auth configure-docker --quiet
      gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_ZONE --project $GCP_PROJECT

jobs:
  build:
    working_directory: ~/customer_registry_service
    docker:
      - image: circleci/openjdk:8
      - image: circleci/mongo:4.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - app-cache-{{ checksum "build.sbt" }}
            - app-cache-v1

      - save_cache:
          key: app-cache-{{ checksum "build.sbt" }}
          paths:
            - target/resolution-cache
            - target/streams
            - project/target/resolution-cache
            - project/target/streams
            - ~/.sbt
            - ~/.ivy2/cache
      - save_cache:
          # Change this key to start the next build with a fully clean cache and forget old scala, sbt and library versions
          key: app-cache-v1
          paths:
            - ~/.sbt
            - ~/.ivy2/cache

      - run:
          name: "Unit tests"
          command:
            sbt unit exit

      - run:
          name: "Integration tests"
          command:
            sbt integration exit

      - store_test_results:
          path: target/test-reports

  push-container:
    docker:
      - image: joseronierison/scala-sbt:scala-2.11
    working_directory: ~/customer_registry_service
    environment:
      ARTIFACT_NAME: *container_name
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: "Build container"
          command: |
            export GIT_COMMIT=$CIRCLE_SHA1
            sbt docker:publishLocal

      - *setup_gcp_credentials

      - run:
          name: "Publish docker container"
          command: |
            docker tag customer_registry_service:$CIRCLE_SHA1 $ARTIFACT_NAME:$CIRCLE_SHA1
            gcloud docker -- push $ARTIFACT_NAME:$CIRCLE_SHA1

  deploy-to-staging:
    docker:
      - image: joseronierison/scala-sbt:scala-2.11
    working_directory: ~/customer_registry_service
    environment:
      ARTIFACT_NAME: *container_name
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - *setup_gcp_credentials

      - run:
          name: "Deploy to staging"
          command: |
            kubectl set image deployments/$K8S_DEPLOYMENT_NAME $K8S_CONTAINER_NAME=$ARTIFACT_NAME:$CIRCLE_SHA1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - push-container:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-to-staging:
          requires:
            - push-container
            filters:
              branches:
                only: master